/**
 *
 * @author Hector Rodriguez
 */
package com.zazil.dwh.app.gui;

import com.zazil.dwh.app.gui.bancos.SaldosEmpresaVentana;

public class MenuPrincipalVentana extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalVentana
     */
    public MenuPrincipalVentana() {
        //this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtSaldosEmpresa = new javax.swing.JButton();
        jbtDeclaraciones = new javax.swing.JButton();
        jbtOperaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DataWareHouse - 2014");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione Operacion", 0, 0, new java.awt.Font("Arial", 0, 12), java.awt.Color.blue)); // NOI18N

        jbtSaldosEmpresa.setText("Saldos");
        jbtSaldosEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaldosEmpresaActionPerformed(evt);
            }
        });

        jbtDeclaraciones.setText("Declaraciones");
        jbtDeclaraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeclaracionesActionPerformed(evt);
            }
        });

        jbtOperaciones.setText("Operaciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtSaldosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtDeclaraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSaldosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtDeclaraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSaldosEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaldosEmpresaActionPerformed
        // TODO Terminado - Hector Giovanni Rodriguez Ramos 18/11/2013
        //Ocultamos ventana padre
        this.setVisible(false);
        //Visualizamos cuadro de diálogo
        SaldosEmpresaVentana saldosEmpresa = new SaldosEmpresaVentana(this, true);
        saldosEmpresa.setVisible(true);
    }//GEN-LAST:event_jbtSaldosEmpresaActionPerformed

    private void jbtDeclaracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeclaracionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtDeclaracionesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtDeclaraciones;
    private javax.swing.JButton jbtOperaciones;
    private javax.swing.JButton jbtSaldosEmpresa;
    // End of variables declaration//GEN-END:variables
}
