INSERT INTO Banco VALUES (464,'IXE','B');
INSERT INTO Banco VALUES (476,'BBVA','B');
INSERT INTO Banco VALUES (537,'CI','B');
INSERT INTO Banco VALUES (564,'IXE','B');
INSERT INTO Banco VALUES (579,'IXE','B');
INSERT INTO Banco VALUES (585,'CI','B');

